config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#dashboard'

  namespace :api do
    namespace :v1 do
      get  '/:user_id/clocked_ins',     to: 'sleeps#clocked_ins',     as: 'clocked_ins'
      get  '/:user_id/friends_records', to: 'sleeps#friends_records', as: 'friends_records'

      post   '/:user_id/follow/:following_id',   to: 'users#follow',   as: 'follow'
      delete '/:user_id/unfollow/:following_id', to: 'users#unfollow', as: 'unfollow'
      post   '/:user_id/sleep',                  to: 'users#sleep',    as: 'sleep'
      post   '/:user_id/wake_up',                to: 'users#wake_up',  as: 'wake_up'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/following.rb
class Following < ApplicationRecord
  belongs_to :user
end

app/models/sleep.rb
class Sleep < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  ONE_WEEK_DAYS = 7

  has_many :followings,  dependent: :destroy
  has_many :sleeps, dependent: :destroy

  def last_sleep
    sleeps.last
  end

  def last_week_records
    sleeps.where("start_time >= ?", ONE_WEEK_DAYS.days.ago)
  end

  def last_week_records_by_length
    last_week_records.order(:length).reverse
  end
end

app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action      :get_users

  include ExceptionHandler

  def get_users
    @user            = User.find params[:user_id]
    @user_following  = User.find params[:following_id] if params[:following_id]
  end
end

app/controllers/api/v1/sleeps_controller.rb
class Api::V1::SleepsController < Api::BaseController
  # Get all clocked ín times
  def clocked_ins
    render json: { message: 'Successfully retrieved clocked ins.', user_id: @user.id, sleepings: @user.sleeps.order(:created_at).as_json, status: :ok }
  end

  # List friends' sleeping records the past week and have them sorted by sleep length.
  def friends_records
    user_followings              = User.where(id: @user.followings.map(&:following_id))
    followings_last_week_records = user_followings.map { |user_following| user_following.last_week_records_by_length }

    render json: { message: 'Successfully retrieved friends records', user_id: @user.id, sleepings: followings_last_week_records.as_json, status: :ok }
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::BaseController
  # Follow a user.
  def follow
    Following.create(user_id: @user.id, following_id: @user_following.id)

    render json: { message: 'Successfully followed a user.', user_id: @user.id, following_id: @user_following.id, status: :ok }
  end

  # Unfollow a user.
  def unfollow
    following = Following.find_by user_id: @user.id, following_id: @user_following.id

    if following
      following.destroy

      render json: { message: 'Successfully unfollowed a user.', user_id: @user.id, following_id: @user_following.id, status: :ok }
    else
      render json: { message: 'Error unfollowing. No such relationship found.', status: :not_found }
    end
  end

  # Set the sleep time
  def sleep
    Sleep.create(user_id: @user.id, start_time: Time.current )

    render json: { message: 'Successfully set the sleep time', user_id: @user.id, status: :ok }
  end

  # Set the wake up time
  def wake_up
    sleeping = Sleep.find_by(user_id: @user.id, end_time: nil)

    if sleeping
      sleeping.update(end_time: Time.current, length: ((Time.current - sleeping.start_time) / 3600).round)

      render json: { message: 'Successfully set the wake up time', user_id: @user.id, status: :ok }
    else
      render json: { message: 'Error setting wake up time. No corresponding sleep time.', user_id: @user.id, status: :not_found }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/concerns/exception_handler.rb
module ExceptionHandler
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound do |e|
      render json: { message: e.message, status: :not_found }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoodNight</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<h2>Good Night</h2>
<hr />

<div class='actions'>
  <h3>Users and actions</h3>
  <%- @users.each do |user| %>
    <p>
      <%= user.id %>: <%= user.name %>
      |
      <%= link_to 'Sleep', api_v1_sleep_path(user.id), remote: true, method: 'POST', onclick: "$(this).remove()" %>
      |
      <%= link_to 'Wake up', api_v1_wake_up_path(user.id), remote: true, method: 'POST', onclick: "$(this).remove()" %>
      |
      <%= link_to 'All clocked ins', api_v1_clocked_ins_path(user.id), remote: true, method: 'GET' %>
      |
      <%= link_to 'Follow someone', api_v1_follow_path(user.id, (User.ids - [user.id, user.followings.pluck(:following_id)]).sample), remote: true, method: 'POST' %>
      |
      <%= link_to 'Unfollow someone', api_v1_unfollow_path(user.id, user.followings.pluck(:following_id).sample), remote: true, method: 'DELETE' unless user.following_ids.blank? %>
      |
      <%= link_to 'Friends records', api_v1_friends_records_path(user.id), remote: true, method: 'GET' unless user.following_ids.blank? %>
    </p>
  <%- end %>
</div>

<div class='results'>
  <h3>Database info</h3>
  <%- @users.each do |user| %>
    <p>
      ID: <%= user.id %>, start_time: <%= user.last_sleep.try(:start_time) %>; end_time: <%= user.last_sleep.try(:end_time) %>, length: <%= user.last_sleep.try(:length) %>
      <br />

      Followings: <%= user.followings.pluck(:following_id).join(', ') %>
    </p>
  <%- end %>
</div>